default_stages: [commit]
exclude: |
  (?x)(
    ^data/ |
    ^\.mypy_cache/ |
    ^venv/ | ^\.venv/ |
    ^.*\.zip$ |
    ^velos\.db$ |
    ^data/snapshots/ |
    ^data/reports/ |
    ^data/logs/
  )

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
        files: ^.*\.(ya?ml)$

  - repo: local
    hooks:
      - id: velos-schema-guard
        name: VELOS Schema Guard
        entry: python scripts/py/check_schema_guard.py
        language: system
        pass_filenames: false
        always_run: true
        
      - id: velos-fts-smoke
        name: VELOS FTS Smoke Test
        entry: python scripts/py/fts_smoke_test.py
        language: system
        pass_filenames: false
        always_run: true
