[tool.mypy]
python_version = "3.11"
ignore_missing_imports = false
namespace_packages = true
explicit_package_bases = true
mypy_path = ["C:\\giwanos"]
warn_unused_ignores = true

[[tool.mypy.overrides]]
module = ["requests", "requests.*"]
ignore_missing_imports = true




[tool.ruff]
line-length = 100
target-version = "py311"

[tool.ruff.lint]
# Guard 통과를 위한 경고성 규칙 무시(필요시만 유지)
ignore = ["E203","E501","PLR0911","PLW2901","PLR2004","SIM105"]
