features:
- description: 리포트 생성 및 이메일 알림 파이프라인
  enabled: true
  keep_patterns:
  - modules/report/**
  - tools/notifications/send_email.py
  - tools/notifications/system_alert_notifier.py
  name: reports_pipeline
- description: VELOS 대시보드 인터페이스
  enabled: true
  keep_patterns:
  - interface/**
  name: dashboard_runtime
- description: VELOS 브리지 자동 시작 스크립트
  enabled: true
  keep_patterns:
  - scripts/start_velos_bridge.ps1
  - scripts/velos_master_loop_wrapper.ps1
  name: bridge_autostart
- description: 세션/메모리 관리 핵심 모듈
  enabled: true
  keep_patterns:
  - modules/core/session_store.py
  - data/memory/**
  name: session_memory_core
- description: 시스템 헬스 체크 및 모니터링
  enabled: true
  keep_patterns:
  - scripts/velos_health_check.ps1
  - scripts/velos_cursor_health_check.ps1
  name: health_monitoring
- description: Windows 스케줄러 태스크 관리
  enabled: true
  keep_patterns:
  - scripts/velos_session_merge.bat
  - velos_session_merge.bat
  name: scheduled_tasks
- description: 파일 사용성 감사 도구
  enabled: true
  keep_patterns:
  - tools/analysis/file_usage_audit.py
  - scripts/run_file_usage_audit.ps1
  name: file_audit_tools
- description: Cursor IDE 통합 설정
  enabled: true
  keep_patterns:
  - .cursorrules
  - .vscode/tasks.json
  - scripts/velos_cursor_checklist.md
  - scripts/velos_cursor_usage.md
  name: cursor_integration
- description: 런타임 트레이스에서 자동 감지된 파일들
  enabled: true
  keep_patterns:
  - C:\Users\User\AppData\Local\Programs\Python\Python311\DLLs\_asyncio.pyd
  - C:\Users\User\AppData\Local\Programs\Python\Python311\DLLs\_ctypes.pyd
  - C:\Users\User\AppData\Local\Programs\Python\Python311\DLLs\_decimal.pyd
  - C:\Users\User\AppData\Local\Programs\Python\Python311\DLLs\_hashlib.pyd
  - C:\Users\User\AppData\Local\Programs\Python\Python311\DLLs\_overlapped.pyd
  - C:\Users\User\AppData\Local\Programs\Python\Python311\DLLs\_queue.pyd
  - C:\Users\User\AppData\Local\Programs\Python\Python311\DLLs\_socket.pyd
  - C:\Users\User\AppData\Local\Programs\Python\Python311\DLLs\_ssl.pyd
  - C:\Users\User\AppData\Local\Programs\Python\Python311\DLLs\_uuid.pyd
  - C:\Users\User\AppData\Local\Programs\Python\Python311\DLLs\_zoneinfo.pyd
  - C:\Users\User\AppData\Local\Programs\Python\Python311\DLLs\select.pyd
  - C:\Users\User\AppData\Local\Programs\Python\Python311\DLLs\unicodedata.pyd
  - C:\Users\User\AppData\Local\Programs\Python\Python311\Lib/**
  - C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\asyncio/**
  - C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\collections/**
  - C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\concurrent/**
  - C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures/**
  - C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ctypes/**
  - C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\email/**
  - C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\encodings/**
  - C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\importlib/**
  - C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\importlib\metadata/**
  - C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\importlib\resources/**
  - C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\json/**
  - C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\logging/**
  - C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\re/**
  - C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\urllib/**
  - C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\zoneinfo/**
  - C:\Users\User\venvs\velos\Lib\site-packages/**
  - C:\Users\User\venvs\velos\Lib\site-packages\blinker/**
  - C:\Users\User\venvs\velos\Lib\site-packages\cachetools/**
  - C:\Users\User\venvs\velos\Lib\site-packages\click/**
  - C:\Users\User\venvs\velos\Lib\site-packages\dateutil/**
  - C:\Users\User\venvs\velos\Lib\site-packages\dateutil\parser/**
  - C:\Users\User\venvs\velos\Lib\site-packages\dateutil\tz/**
  - C:\Users\User\venvs\velos\Lib\site-packages\google\protobuf/**
  - C:\Users\User\venvs\velos\Lib\site-packages\google\protobuf\internal/**
  - C:\Users\User\venvs\velos\Lib\site-packages\google\protobuf\pyext/**
  - C:\Users\User\venvs\velos\Lib\site-packages\numpy/**
  - C:\Users\User\venvs\velos\Lib\site-packages\numpy\_core/**
  - C:\Users\User\venvs\velos\Lib\site-packages\numpy\_core\_multiarray_umath.cp311-win_amd64.pyd
  - C:\Users\User\venvs\velos\Lib\site-packages\numpy\_typing/**
  - C:\Users\User\venvs\velos\Lib\site-packages\numpy\_utils/**
  - C:\Users\User\venvs\velos\Lib\site-packages\numpy\lib/**
  - C:\Users\User\venvs\velos\Lib\site-packages\numpy\linalg/**
  - C:\Users\User\venvs\velos\Lib\site-packages\numpy\ma/**
  - C:\Users\User\venvs\velos\Lib\site-packages\numpy\matrixlib/**
  - C:\Users\User\venvs\velos\Lib\site-packages\numpy\random/**
  - C:\Users\User\venvs\velos\Lib\site-packages\numpy\random\_generator.cp311-win_amd64.pyd
  - C:\Users\User\venvs\velos\Lib\site-packages\numpy\random\_mt19937.cp311-win_amd64.pyd
  - C:\Users\User\venvs\velos\Lib\site-packages\numpy\random\_pcg64.cp311-win_amd64.pyd
  - C:\Users\User\venvs\velos\Lib\site-packages\numpy\random\_philox.cp311-win_amd64.pyd
  - C:\Users\User\venvs\velos\Lib\site-packages\numpy\random\_sfc64.cp311-win_amd64.pyd
  - C:\Users\User\venvs\velos\Lib\site-packages\numpy\random\bit_generator.cp311-win_amd64.pyd
  - C:\Users\User\venvs\velos\Lib\site-packages\numpy\random\mtrand.cp311-win_amd64.pyd
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas/**
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas\_config/**
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas\_libs/**
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas\_libs\algos.cp311-win_amd64.pyd
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas\_libs\arrays.cp311-win_amd64.pyd
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas\_libs\hashing.cp311-win_amd64.pyd
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas\_libs\hashtable.cp311-win_amd64.pyd
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas\_libs\indexing.cp311-win_amd64.pyd
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas\_libs\internals.cp311-win_amd64.pyd
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas\_libs\interval.cp311-win_amd64.pyd
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas\_libs\json.cp311-win_amd64.pyd
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas\_libs\lib.cp311-win_amd64.pyd
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas\_libs\missing.cp311-win_amd64.pyd
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas\_libs\ops_dispatch.cp311-win_amd64.pyd
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas\_libs\parsers.cp311-win_amd64.pyd
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas\_libs\properties.cp311-win_amd64.pyd
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas\_libs\sparse.cp311-win_amd64.pyd
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas\_libs\tslibs/**
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas\_libs\tslibs\ccalendar.cp311-win_amd64.pyd
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas\_libs\tslibs\conversion.cp311-win_amd64.pyd
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas\_libs\tslibs\dtypes.cp311-win_amd64.pyd
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas\_libs\tslibs\fields.cp311-win_amd64.pyd
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas\_libs\tslibs\nattype.cp311-win_amd64.pyd
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas\_libs\tslibs\np_datetime.cp311-win_amd64.pyd
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas\_libs\tslibs\offsets.cp311-win_amd64.pyd
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas\_libs\tslibs\parsing.cp311-win_amd64.pyd
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas\_libs\tslibs\period.cp311-win_amd64.pyd
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas\_libs\tslibs\strptime.cp311-win_amd64.pyd
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas\_libs\tslibs\timedeltas.cp311-win_amd64.pyd
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas\_libs\tslibs\timestamps.cp311-win_amd64.pyd
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas\_libs\tslibs\timezones.cp311-win_amd64.pyd
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas\_libs\tslibs\tzconversion.cp311-win_amd64.pyd
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas\_libs\tslibs\vectorized.cp311-win_amd64.pyd
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas\_libs\window\indexers.cp311-win_amd64.pyd
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas\_libs\writers.cp311-win_amd64.pyd
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas\_testing/**
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas\api/**
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas\arrays/**
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas\compat/**
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas\compat\numpy/**
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas\core/**
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas\core\_numba/**
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas\core\array_algos/**
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas\core\arrays/**
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas\core\arrays\arrow/**
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas\core\arrays\sparse/**
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas\core\computation/**
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas\core\dtypes/**
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas\core\groupby/**
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas\core\indexers/**
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas\core\indexes/**
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas\core\interchange/**
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas\core\internals/**
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas\core\methods/**
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas\core\ops/**
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas\core\reshape/**
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas\core\strings/**
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas\core\tools/**
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas\core\util/**
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas\core\window/**
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas\errors/**
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas\io/**
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas\io\excel/**
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas\io\formats/**
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas\io\json/**
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas\io\parsers/**
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas\io\sas/**
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas\plotting/**
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas\tseries/**
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas\util/**
  - C:\Users\User\venvs\velos\Lib\site-packages\pandas\util\version/**
  - C:\Users\User\venvs\velos\Lib\site-packages\pyarrow/**
  - C:\Users\User\venvs\velos\Lib\site-packages\pyarrow\_compute.cp311-win_amd64.pyd
  - C:\Users\User\venvs\velos\Lib\site-packages\pyarrow\_feather.cp311-win_amd64.pyd
  - C:\Users\User\venvs\velos\Lib\site-packages\pyarrow\lib.cp311-win_amd64.pyd
  - C:\Users\User\venvs\velos\Lib\site-packages\pyarrow\vendored/**
  - C:\Users\User\venvs\velos\Lib\site-packages\pytz/**
  - C:\Users\User\venvs\velos\Lib\site-packages\streamlit/**
  - C:\Users\User\venvs\velos\Lib\site-packages\streamlit\commands/**
  - C:\Users\User\venvs\velos\Lib\site-packages\streamlit\components\lib/**
  - C:\Users\User\venvs\velos\Lib\site-packages\streamlit\components\types/**
  - C:\Users\User\venvs\velos\Lib\site-packages\streamlit\components\v1/**
  - C:\Users\User\venvs\velos\Lib\site-packages\streamlit\connections/**
  - C:\Users\User\venvs\velos\Lib\site-packages\streamlit\elements/**
  - C:\Users\User\venvs\velos\Lib\site-packages\streamlit\elements\lib/**
  - C:\Users\User\venvs\velos\Lib\site-packages\streamlit\elements\widgets/**
  - C:\Users\User\venvs\velos\Lib\site-packages\streamlit\navigation/**
  - C:\Users\User\venvs\velos\Lib\site-packages\streamlit\proto/**
  - C:\Users\User\venvs\velos\Lib\site-packages\streamlit\runtime/**
  - C:\Users\User\venvs\velos\Lib\site-packages\streamlit\runtime\caching/**
  - C:\Users\User\venvs\velos\Lib\site-packages\streamlit\runtime\caching\storage/**
  - C:\Users\User\venvs\velos\Lib\site-packages\streamlit\runtime\scriptrunner/**
  - C:\Users\User\venvs\velos\Lib\site-packages\streamlit\runtime\scriptrunner_utils/**
  - C:\Users\User\venvs\velos\Lib\site-packages\streamlit\runtime\state/**
  - C:\Users\User\venvs\velos\Lib\site-packages\streamlit\watcher/**
  - C:\Users\User\venvs\velos\Lib\site-packages\yaml/**
  - C:\Users\User\venvs\velos\Lib\site-packages\yaml\_yaml.cp311-win_amd64.pyd
  - modules\logs/**
  - modules\tags/**
  - modules\utils/**
  - modules\vectors/**
  last_sync: '2025-08-17T00:14:57'
  name: runtime_trace
  synced_files_count: 787
- name: users_runtime
  enabled: true
  keep_patterns:
  - Users/*/AppData/Local/giwanos/**
  - configs/settings.yaml/**
  - data/memory/**
  - data/snapshots/**
  - modules/logs/**
  - modules/tags/**
  - modules/utils/**
  - modules/vectors/**
- name: auto_runtime_trace
  enabled: true
  keep_patterns:
  - C:\/Users/**
  - configs/settings.yaml/**
  - data/memory/**
  - data/snapshots/**
  - modules/logs/**
  - modules/tags/**
  - modules/utils/**
  - modules/vectors/**
global:
  exclude_patterns:
  - configs/**
  - .git/**
  - data/logs/**
  - data/snapshots/**
  - data/reports/**
  - '*.pyc'
  - __pycache__/**
  - .vscode/**
  - .cursorrules
  - README.md
  - requirements.txt
  - '*.bat'
  - '*.ps1'
  whitelist_priority: 100
