# VELOS 메모리 스키마 정의
memory_types:
  session:
    fields:
      - id: string
      - timestamp: datetime
      - content: text
      - tags: array
  reflection:
    fields:
      - id: string
      - timestamp: datetime
      - insight: text
      - confidence: float









