name: VELOS CI

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install slack_sdk pytest

      - name: Run tests
        run: pytest -q

      - name: Report success to Slack
        if: success()
        run: |
          python - <<'PY'
          from tools.notifications.slack_api import send
          import os
          sha = os.environ['GITHUB_SHA'][:7]
          send(f"✅ VELOS CI passed for commit {sha}")
          PY
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}

      - name: Report failure to Slack
        if: failure()
        run: |
          python - <<'PY'
          from tools.notifications.slack_api import send
          import os
          sha = os.environ['GITHUB_SHA'][:7]
          send(f"❌ VELOS CI failed for commit {sha}")
          PY
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
