jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest -q
      - name: Report success to Slack
        if: success()
        run: |
          python - <<'PY'
          from tools.notifications.slack_api import send
          import os
          send(f"✅ VELOS CI passed for commit {os.environ['GITHUB_SHA'][:7]}")
          PY
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
      - name: Report failure to Slack
        if: failure()
        run: |
          python - <<'PY'
          from tools.notifications.slack_api import send
          import os
          send(f"❌ VELOS CI failed for commit {os.environ['GITHUB_SHA'][:7]}")
          PY
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
